@startuml
'https://plantuml.com/component-diagram

!theme mars

title "Incite component diagram"

node "JVM" {
    package "Spring Boot" {
        component "Apache Camel" as camel
        component "Apache Ignite" as ignite
        component "Apache Spark" as spark
        component "Incite" as incite
        component "Jersey 2" as jersey2

        interface "tcp" as tcp0
        interface "tcp" as tcp1

       http - jersey2
       jersey2 <--> incite
       incite ..> camel : use
       incite ..> ignite : use
       incite ..> spark : use

       jdbc -right- ignite
       odbc -down- ignite
       tcp0 -up- ignite
       tcp1 -up- camel
    }
}

@enduml