@startuml
'https://plantuml.com/deployment-diagram

!theme mars

title "Incite example deployment diagram"

cloud "Cloud/Internal data centre" {

    node "Docker/K8s" {
        node "Container 0" {
            node "JVM" {
                package "Spring Boot" {
                    component "Apache Camel" as camel
                    component "Apache Ignite" as ignite
                    component "Apache Spark" as spark
                    component "Incite" as incite
                    component "Jersey 2" as jersey2

                    interface "tcp" as tcp0

                   http -- jersey2
                   jersey2 <--> incite
                   incite <--> camel
                   incite <-right-> ignite
                   incite <--> spark

                   jdbc -- ignite
                   odbc -left- ignite
                   tcp0 -up- ignite
                }
            }
        }

        node "Container 1" {
            database "Kafka" as kafka
        }

        note left of kafka: Optional
    }

    database "RDBMS" as rdbms

    note left of rdbms: Optional

    node "NFS/S3" {
        folder "spark-checkpoints" as sparkCheckPointsFolder
    }

    camel <--> kafka
    spark <-up-> sparkCheckPointsFolder
    spark <--> kafka
    spark <-left-> rdbms
}
@enduml